Fixed an exception and possible memory leak in Python 3.11.1+ -- by :user:`Dreamsorcerer`
